### PR TITLE
autodetection for simple-schema and collection2: will enable filter and ...

### PR DESCRIPTION
**Pull request by krawalli**
...validate settings and will send possible validation errors back to context.

So the result could be picked up by afterInsert / afterUpdate callback (e.g. to display alerts to user why the update failed)

### CODE REVIEW

**Comment by JackAdams** [comment]
Yep, I see the value in this. Just a couple of things before I merge it:

1) `EditableText.config({collection2Options:{filter: true, validate: true, tri: 'tra', tru: 'lala'}});` -- what are the third and fourth parameter there for?  Is this line actually necessary in the `lib/editable_text_server.js` file? (I'm guessing it is for the autodetection to work.)
2) Have you tested these changes on an app with and without the collection2/simple-schema package to make sure the package still works either way? (I'll be doing some testing myself, but just interested.)
3) I'm pretty sure `this.collection2Options` should be `EditableText.collection2Options` in lines 197 and 249 of `editable-text-common.js`, as `this` is undefined in that context, if I remember right.

**Comment by krawalli** [comment]
those extra parameter are nonsense - fragments from testing. Sorry there is one commit missing in thi pull request.

Your source is hard to read, cause you are not using indents etc. 
If you dont mind i would like to put some basic formatted in a extra pull request.

I've run a test with and without and it was ok, but please verify it running.

**Comment by JackAdams** [comment]
Thanks for the heads-up about the crappy code formatting.  When coding, I religiously 2-space indent everything and keep it all readable, but what I'm seeing in my editor and what I'm pushing to github are obviously two different things. Don't worry about cleaning up the formatting. I'll see to that.

**Comment by JackAdams** [comment]
Merged manually.  In the latest release.  Code should be indented properly now too.

**Pull request closed without merging**
